### ISSUE TITLE
FEAT: Support *.sql sqlite files as well as *.db

### ISSUE THREAD

**Issue by vtnate** [dbgate/dbgate#149]
**Is your feature request related to a problem? Please describe.**
SQLite files appear to be only supported with the `*.db` filetype. A `*.sql` file doesn't open as a database

**Describe the solution you'd like**
SQLite files with `*.sql` filetype open the same way `*.db` files open.

**Describe alternatives you've considered**
Manually renaming files to change the filetype works.

**Comment by janproch** [comment]
Default meaning of *.sql is text file with SQL code. You can open .sql files with SDQLite database in DbGate, but it is not possible to open them with drag & drop, you have to use "Add connection" dialog, choose SQLite connection and select your .sql file. In this case, any extension could be used for SQLite database.

**Comment by vtnate** [comment]
When I do the "Add connection" dialog my *.sql file is greyed out, appearing to be not openable by dbgate. Same greyed-out behavior when I rename the file to *.db, but in that case I am able to drag and drop to open the *.db file.

**Comment by janproch** [comment]
What is you operating system? I have tested it on ubuntu linux and on windows, and it worked correctly - it offers all file types.

See attached image, to make sure, that we talk about the same dialog.

![image](https://user-images.githubusercontent.com/2543891/130128857-fd785ab2-537e-4953-b30f-2dbe26252bfa.png)

**Comment by vtnate** [comment]
Ah, yes. I'm using Mac OSX 10.14.6 (Mojave). We are talking about the same dialog. When I click `browse` in step 3 of your image, the *.db/*.sql file is greyed out and not available to select.

**Comment by janproch** [comment]
Is should be fixed in most recent BETA version, 4.2.8-beta.3. Sorry for late response

**Comment by janproch** [comment]
Released in version 4.3.0

**Comment by vtnate** [comment]
@janproch This still doesn't work for me (MacOS 10.15.7, dbgate 4.6.1). If using the `Add New Connection` dialog mentioned above, the `*.sql` file is greyed-out and unavailable. Drag-and-drop the sql file also doesn't work, which I believe is expected. When I change the filename to `*.db` the dialog continues to show the file greyed-out and unavailable, but drag-and-drop of the .db file works as expected.

Is this something I should just deal with, or is there a relatively easy way to support `*.sql` files on macos?

**Comment by janproch** [comment]
Thanks for message

It seems that my fix doesn't work. It should be quite easy to fix it, unfortunately today I don't have access to any Mac hardware, so till I will handle this, it is difficult for me to fix it. Drag & drop for .sql files will not work, but opening from connection dialog should work, only it is neccessary to properly configure electron save dialog.

Probably the same problem is in issue #206
