### ISSUE TITLE
BUG: Error opening SQLite file

### ISSUE THREAD

**Issue by asitemade4u** [dbgate/dbgate#219]
I am sorry to reopen bug #215  but even after updating to the latest version I still have difficulties accessing a SQLite file.

- same config as in #215
- I changed the permissions of the mounted directory where the database file is located to `root`
- I can now see the database in DBGate's interface allright: it has a specific yellow icon
- BUT the structure is not displayed: a `Loading database structure` message is displayed and goes forever.

Questions:

- do I have to stop the database that is using the database file? In other terms, is there a lock on SQLite files?
- are the file permissions I am using correct?

**Comment by janproch** [comment]
I have also seen this bug, but now I am unable to reproduce this

If you try to reconnect (eg. with refresh button on table list), does it help?

It effectively kills the process with (probably) locked connection and open new connection

There should be no exclusive lock on SQLite file, probably only when there is an open transaction

![image](https://user-images.githubusercontent.com/2543891/153379888-724b8065-ae15-416f-9bd4-1c72caacc273.png)

**Comment by janproch** [comment]
I came across similar issue in MySQL, I believe that it is fixed now in newest BETA, 4.6.4-beta.1

The reason were race conditions in cache subsystem. It occured when using very fast SQL connections (eg SQLite)

**Comment by janproch** [comment]
Yes, you can try it now, beta versions are published to Docket Hub with beta tag

docker pull dbgate/dbgate:beta

**Comment by asitemade4u** [comment]
Hi, I am sorry but it still does not work with the beta version.
I took the steps of pruning the old version from docker before + empty 
the browser cache so no risk of interference.

S.

**Comment by janproch** [comment]
Hi, OK, thanks for test

I have a few questions:
1. If you refresh tables (on image is button marked as Reconnect), does it show tables?
2. If you refresh page in browser (with browse native Refreh button, keyboard shortcuts are remapped by DbGate), deos it help?
3. Did you see structure if this SQLite database in DbGate sometimes? Or it shows "Loading tables" every time?
4. If you are in correct state (tables are shown) and click "Reload model" repeatedly, does it hang up and show "Loading tables" idenfinitely sometimes?
5. Are there any errors in browser console? (press F12, tab Console)

If we will not be able to solve this, I would like to add some logging options
Thanks

![image](https://user-images.githubusercontent.com/2543891/153698349-4dcabc48-c102-4264-83d7-07f6657b68c9.png)

**Comment by janproch** [comment]
OK thanks for info. The problem is in dbgate docker image, there is incorrect sqlite package. I am trying to fix it

**Comment by asitemade4u** [comment]
Ah yes, that is probably the case.

**Comment by janproch** [comment]
Current beta version of Docker image should be fixed, SQLite works

docker pull dbgate/dbgate:beta

SQLite doesn't work in alpine image, so 2 images are build: beta and beta-alpine. If you want to use SQLite, use non-alpine version

**Comment by asitemade4u** [comment]
Hi Jan,

IT WORKS!!!
I really appreciate your help and the quality of your support.

Best,

Stephen

**Comment by janproch** [comment]
Released in 4.7.0
