### ISSUE TITLE
BUG: [object Object] for Column filter for binary IDs

### ISSUE THREAD

**Issue by Zerotask** [dbgate/dbgate#467]
**Describe the bug**
We're using Shopware and they heavily use binary IDs for their tables.
When I open an entry inside a table, I see [object Object]

If I click on a reference table, it also tries to find an ID [object Object]

**To Reproduce**
1. Open a table
2. Click on an entry
3. See [object Object] on the Column filter

**Expected behavior**
Resolve / link those binary IDs probably.

**Screenshots**
![image](https://user-images.githubusercontent.com/20150243/214267088-211b17be-8fd0-4532-9f72-03381224c1f0.png)

![image](https://user-images.githubusercontent.com/20150243/214267341-06677899-2763-441e-a665-0cc1e50190db.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 5.2.1
 - Install source: installer
 - Type: Application
 - Database engine: MySQL 5.7.40

**Comment by janproch** [comment]
Added support for binary filters. Thanks for the idea

![image](https://user-images.githubusercontent.com/2543891/215265239-d45c7fd6-572b-481e-acc5-eff7b57f24eb.png)

**Comment by Zerotask** [comment]
I found another related bug.

I copied the hexadecimal representation of a binary ID (e. g. 0xB0E6691C5C0942F3B29A25BE9AC6F3C3) and tried to use it to filter another table which has a reference on it.
The binary ID on the other table is present, but it shows 0 results:

### Table A
![image](https://user-images.githubusercontent.com/20150243/215266527-c93c725a-5bd0-4adc-9c9f-ae6047b1aa24.png)

### Table B
![image](https://user-images.githubusercontent.com/20150243/215266551-a4c06d12-da3d-4e5d-8084-d0830d23da82.png)

![image](https://user-images.githubusercontent.com/20150243/215266561-dca55791-1d61-41a6-89f8-014889061789.png)

**Comment by janproch** [comment]
This issue is also fixed in newest BETA

**Comment by allen-pattern** [comment]
I still see this on Context menu > Edit Cell Value on a cell with a binary value.
