### ISSUE TITLE
Show query in single tab

### ISSUE THREAD

**Issue by krujjwal88** [dbgate/dbgate#64]
It is  a good product. Appreceiate for development.
Please develop a feature so that one can see multiple multiple query output in a single tab. like select 1; select 2
the result should come one above another on the same tab.
Thank you in advance

**Comment by janproch** [comment]
Thanks for feedback. Planned milestone - 4.1.0

Idea:  
First tab will be "All results" with all results one above another (maybe grids will be without column list in this view), other tabs remain unchanged

**Comment by janproch** [comment]
Part of released version 4.1.0

**Comment by janproch** [comment]
done

**Comment by krujjwal88** [comment]
Hi Team,
Still not working in version 4.1.8.

________________________________________________________________________________
Thanks & Regards:
KUMAR UJJWAL
call:- +91-9555695547
________________________________

**Comment by janproch** [comment]
Hi,
and have you switched the view?

All results on single tab is not default option. When you switch this once, the option is remembered, so you don't have to switch it always.

![image](https://user-images.githubusercontent.com/2543891/115538019-baa5f100-a29b-11eb-81ad-1722c63b1f61.png)

**Comment by krujjwal88** [comment]
Thank you for the support. Appreciate the effort. Good work. Keep it up.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
